name: Deploy to AWS EC2

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, World!"
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Test aws cli
        run: aws --version

      # - name: Deploy to AWS EC2
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set default.region ${{ secrets.AWS_REGION }}
          
      #     aws s3 cp ./ s3://mybucket/ --recursive  # Replace 'mybucket' with your bucket's name
          
      #     aws s3 sync s3://mybucket/ /var/www/html/  # Replace 'mybucket' and '/var/www/html/' with your bucket's name and your target directory on EC2
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
